[package]
name = "search"
version = "0.1.0"
authors = ["joe"]

[dependencies]
getopts = "0.2"
env_logger = "0.4"
log = "0.3"
enum_primitive = "0.1.1"
num = "*"
multimap = "*"
time = "*"
openssl = "*"
url = "*"